image: jbweston/tex

job:
  script:
    - make clean
    - make
    - gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=dissertation-compressed.pdf dissertation.pdf

  artifacts:
    paths:
    - dissertation.pdf
    - dissertation-compressed.pdf
